version: "3.1"

services:
    mongo:
        container_name: mongo
        image: mongo:4.4.8
        command:
            - --config
            - /etc/mongod.conf
        volumes:
            - /home/tuana9a/mongod.container.conf:/etc/mongod.conf
        # ports:
        #     - 27017:27017
        network_mode: host
